# Generated by Django 4.0.4 on 2022-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_widgetuser_email_alter_widgetuser_id_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
