# Generated by Django 4.0.4 on 2022-05-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_widgetuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetuser',
            name='profile_pic',
        ),
    ]
