# Generated by Django 4.0.4 on 2022-09-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_widgetuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetuser',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
