# Generated by Django 4.0.3 on 2022-04-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('home_unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='widgetuser',
            name='email',
            field=models.EmailField(default='none', max_length=256),
        ),
        migrations.AddField(
            model_name='widgetuser',
            name='id_num',
            field=models.CharField(default='none', max_length=7),
        ),
        migrations.AddField(
            model_name='widgetuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.department'),
        ),
    ]
