# Generated by Django 4.0.4 on 2022-05-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_widgetuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
