# Generated by Django 4.0.4 on 2022-09-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_widgetuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
