# Generated by Django 4.0.4 on 2022-09-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_widgetuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
